- name: Make folder in Classroom PCs and store file in new folder
  hosts: win
  gather_facts: no  # We don't need to gather facts
  tasks:
    - name: Export file over from Controller
      ansible.windows.win_copy:
        src: /home/administrator/ToPush/kali-linux-2022.2-live-amd64.iso
        dest: D:\ET0741LabFiles\kali-linux-2022.2-live-amd64.iso 