- name: Enable firewall
  hosts: win
  gather_facts: no  # We don't need to gather facts
  tasks:
    - name: Enable firewall for Domain, Public and Private profiles
      community.windows.win_firewall:
        state: enabled
        profiles:
        - Domain
        - Private
        - Public
      tags: enable_firewall