- name: Make folder in Classroom PCs and store file in new folder
  hosts: win
  gather_facts: no  # We don't need to gather facts
  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true

    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      become: true
      become_method: runas
      become_user: SYSTEM